import * as SecureStore from "expo-secure-store";
import React, { useCallback, useEffect, useRef, useState } from "react";
import {
  KeyboardAvoidingView,
  Platform,
  RefreshControl,
  ScrollView,
  StyleSheet,
  Text,
  TextInput,
  TouchableOpacity,
  View,
} from "react-native";
import {
  DailyScore,
  Suggestion,
  generateSuggestion,
  getLatestScores,
  getLatestSuggestion,
  patchExposure,
} from "../api/client";
import { MetricCard } from "../components/MetricCard";
import { RhythmCard } from "../components/RhythmCard";
import { cardBase, colors, font, radius, space } from "../theme";

// ── Task types ────────────────────────────────────────────────────────────────
type Effort = "low" | "medium" | "high";
interface Task { id: string; name: string; effort: Effort }

const EFFORT_EXPOSURE: Record<Effort, number> = { low: 3, medium: 7, high: 12 };
const EFFORT_COLORS: Record<Effort, { bg: string; text: string }> = {
  low:    { bg: "#E8F5EC", text: "#2D6A42" },
  medium: { bg: "#EAF0FB", text: "#2B4A8A" },
  high:   { bg: "#FDF3E7", text: "#8A4E1A" },
};

// ── Persistence ───────────────────────────────────────────────────────────────
async function load(key: string): Promise<string | null> {
  try { return await SecureStore.getItemAsync(key); }
  catch { return null; }
}
async function save(key: string, value: string): Promise<void> {
  try { await SecureStore.setItemAsync(key, value); }
  catch { /* silently fail */ }
}

// ── Greeting ──────────────────────────────────────────────────────────────────
function getGreeting(): string {
  const h = new Date().getHours();
  if (h < 12) return "Good morning, Alana.";
  if (h < 17) return "Good afternoon, Alana.";
  return "Good evening, Alana.";
}

// ── Component ─────────────────────────────────────────────────────────────────
export function TodayScreen() {
  const [scores, setScores] = useState<DailyScore | null>(null);
  const [suggestion, setSuggestion] = useState<Suggestion | null>(null);
  const [scoresLoading, setScoresLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [refreshing, setRefreshing] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const [intention, setIntention] = useState("");
  const [tasks, setTasks] = useState<Task[]>([]);
  const [showTasks, setShowTasks] = useState(false);
  const [isAddingTask, setIsAddingTask] = useState(false);
  const [newTaskName, setNewTaskName] = useState("");
  const [newTaskEffort, setNewTaskEffort] = useState<Effort>("medium");

  const [calendarBase, setCalendarBase] = useState<number | null>(null);
  const hasAutoGenerated = useRef(false);

  // ── Load persisted data ───────────────────────────────────────────────────
  useEffect(() => {
    load("rhythm_intention").then(v => { if (v) setIntention(v); });
    load("rhythm_tasks").then(v => {
      if (v) { try { setTasks(JSON.parse(v)); } catch {} }
    });
  }, []);

  useEffect(() => { save("rhythm_intention", intention); }, [intention]);
  useEffect(() => { save("rhythm_tasks", JSON.stringify(tasks)); }, [tasks]);

  // ── Fetch ─────────────────────────────────────────────────────────────────
  const fetchData = useCallback(async () => {
    setError(null);
    try {
      const [s, sg] = await Promise.allSettled([getLatestScores(), getLatestSuggestion()]);
      if (s.status === "fulfilled") {
        setScores(s.value);
        if (calendarBase === null) setCalendarBase(s.value.exposure_score ?? 40);
      } else {
        setError("Could not reach backend. Is the server running?");
      }
      if (sg.status === "fulfilled") setSuggestion(sg.value);
    } finally {
      setScoresLoading(false);
    }
  }, []);

  useEffect(() => { fetchData(); }, [fetchData]);

  const onRefresh = useCallback(async () => {
    setRefreshing(true);
    await fetchData();
    setRefreshing(false);
  }, [fetchData]);

  // ── Auto-generate once user provides input ────────────────────────────────
  const hasInput = intention.trim().length > 0 || tasks.length > 0;
  useEffect(() => {
    if (hasInput && !hasAutoGenerated.current && scores && !generating) {
      hasAutoGenerated.current = true;
      handleGenerate();
    }
  }, [hasInput, scores]);

  // ── Exposure ──────────────────────────────────────────────────────────────
  const taskImpact = tasks.reduce((sum, t) => sum + EFFORT_EXPOSURE[t.effort], 0);
  const exposureScore = Math.min(100, (calendarBase ?? 40) + taskImpact);

  useEffect(() => {
    if (!scores || calendarBase === null) return;
    const id = setTimeout(() => {
      patchExposure(exposureScore).catch(() => {});
    }, 800);
    return () => clearTimeout(id);
  }, [exposureScore, scores, calendarBase]);

  // ── Generate ──────────────────────────────────────────────────────────────
  async function handleGenerate() {
    if (generating || !scores) return;
    setGenerating(true);
    try {
      const sg = await generateSuggestion();
      setSuggestion(sg);
    } catch { /* no-op */ }
    finally { setGenerating(false); }
  }

  // ── Tasks ─────────────────────────────────────────────────────────────────
  function addTask() {
    if (!newTaskName.trim()) return;
    setTasks(prev => [...prev, {
      id: Date.now().toString(),
      name: newTaskName.trim(),
      effort: newTaskEffort,
    }]);
    setNewTaskName("");
    setNewTaskEffort("medium");
    setIsAddingTask(false);
  }

  function removeTask(id: string) {
    setTasks(prev => prev.filter(t => t.id !== id));
  }

  function updateEffort(id: string, effort: Effort) {
    setTasks(prev => prev.map(t => t.id === id ? { ...t, effort } : t));
  }

  // ── Date ──────────────────────────────────────────────────────────────────
  const dateLabel = new Date().toLocaleDateString("en-US", {
    weekday: "long", month: "long", day: "numeric",
  });

  // ── Render ────────────────────────────────────────────────────────────────
  return (
    <KeyboardAvoidingView
      style={styles.flex}
      behavior={Platform.OS === "ios" ? "padding" : undefined}
    >
      <ScrollView
        style={styles.scroll}
        contentContainerStyle={styles.content}
        refreshControl={<RefreshControl refreshing={refreshing} onRefresh={onRefresh} tintColor={colors.text.muted} />}
        keyboardShouldPersistTaps="handled"
      >

        {/* ── Greeting + date ─────────────────────────────────────────── */}
        <View style={styles.greetingSection}>
          <Text style={styles.dateLabel}>{dateLabel}</Text>
          <Text style={styles.greeting}>{getGreeting()}</Text>
        </View>

        {/* ── Error ── */}
        {error && (
          <View style={styles.errorBanner}>
            <Text style={styles.errorText}>{error}</Text>
          </View>
        )}

        {/* ── Intention ───────────────────────────────────────────────── */}
        <View style={styles.intentionSection}>
          <Text style={styles.intentionPrompt}>What's your main{"\n"}priority today?</Text>
          <TextInput
            style={styles.intentionInput}
            value={intention}
            onChangeText={setIntention}
            placeholder="Type your intention…"
            placeholderTextColor={colors.text.muted}
            returnKeyType="done"
          />
        </View>

        {/* ── Tasks ───────────────────────────────────────────────────── */}
        <View style={styles.section}>
          <TouchableOpacity
            style={styles.tasksToggle}
            onPress={() => setShowTasks(v => !v)}
            activeOpacity={0.7}
          >
            <View style={styles.tasksToggleLeft}>
              <Text style={styles.tasksToggleLabel}>Tasks</Text>
              {tasks.length > 0 && (
                <View style={styles.tasksBadge}>
                  <Text style={styles.tasksBadgeText}>{tasks.length}</Text>
                </View>
              )}
            </View>
            <Text style={styles.chevron}>{showTasks ? "−" : "+"}</Text>
          </TouchableOpacity>

          {showTasks && (
            <View style={styles.tasksBody}>
              {tasks.map((task, i) => (
                <View key={task.id} style={[
                  styles.taskRow,
                  i < tasks.length - 1 && styles.taskRowBorder,
                ]}>
                  <View style={styles.taskContent}>
                    <Text style={styles.taskName}>{task.name}</Text>
                    <View style={styles.effortRow}>
                      {(["low", "medium", "high"] as Effort[]).map(level => (
                        <TouchableOpacity
                          key={level}
                          onPress={() => updateEffort(task.id, level)}
                          style={[
                            styles.effortTag,
                            task.effort === level
                              ? { backgroundColor: EFFORT_COLORS[level].bg }
                              : styles.effortTagInactive,
                          ]}
                        >
                          <Text style={[
                            styles.effortTagText,
                            { color: task.effort === level ? EFFORT_COLORS[level].text : "#8A8A8A" },
                            task.effort === level && { fontWeight: font.weight.semibold },
                          ]}>
                            {level[0].toUpperCase() + level.slice(1)}
                          </Text>
                        </TouchableOpacity>
                      ))}
                    </View>
                  </View>
                  <TouchableOpacity onPress={() => removeTask(task.id)} style={styles.removeBtn}>
                    <Text style={styles.removeBtnText}>×</Text>
                  </TouchableOpacity>
                </View>
              ))}

              {isAddingTask ? (
                <View style={styles.addTaskForm}>
                  <View style={styles.addTaskInputRow}>
                    <TextInput
                      style={styles.addTaskInput}
                      value={newTaskName}
                      onChangeText={setNewTaskName}
                      placeholder="Task name…"
                      placeholderTextColor={colors.text.muted}
                      autoFocus
                      onSubmitEditing={addTask}
                      returnKeyType="done"
                    />
                    <TouchableOpacity onPress={addTask} style={styles.addBtn}>
                      <Text style={styles.addBtnText}>Add</Text>
                    </TouchableOpacity>
                  </View>
                  <View style={styles.effortRow}>
                    {(["low", "medium", "high"] as Effort[]).map(level => (
                      <TouchableOpacity
                        key={level}
                        onPress={() => setNewTaskEffort(level)}
                        style={[
                          styles.effortTag,
                          newTaskEffort === level
                            ? { backgroundColor: EFFORT_COLORS[level].bg }
                            : styles.effortTagInactive,
                        ]}
                      >
                        <Text style={[
                          styles.effortTagText,
                          { color: newTaskEffort === level ? EFFORT_COLORS[level].text : "#8A8A8A" },
                          newTaskEffort === level && { fontWeight: font.weight.semibold },
                        ]}>
                          {level[0].toUpperCase() + level.slice(1)}
                        </Text>
                      </TouchableOpacity>
                    ))}
                  </View>
                  <TouchableOpacity
                    onPress={() => { setIsAddingTask(false); setNewTaskName(""); }}
                    style={styles.cancelBtn}
                  >
                    <Text style={styles.cancelBtnText}>Cancel</Text>
                  </TouchableOpacity>
                </View>
              ) : (
                <TouchableOpacity
                  onPress={() => setIsAddingTask(true)}
                  style={styles.addTaskDashed}
                >
                  <Text style={styles.addTaskDashedText}>+ Add task</Text>
                </TouchableOpacity>
              )}
            </View>
          )}
        </View>

        {/* ── Divider ─────────────────────────────────────────────────── */}
        <View style={styles.divider} />

        {/* ── Metric cards ────────────────────────────────────────────── */}
        <View style={styles.metricsRow}>
          <MetricCard metric="recovery" value={scores?.recovery_score ?? null} loading={scoresLoading} />
          <MetricCard metric="exposure" value={exposureScore} loading={scoresLoading} />
        </View>

        {/* ── Rhythm card ─────────────────────────────────────────────── */}
        <View style={styles.section}>
          <RhythmCard
            condition={scores?.condition ?? null}
            reflection={suggestion?.reflection ?? null}
            bullets={suggestion?.bullets ?? []}
            loading={scoresLoading}
            generating={generating}
            onGenerate={scores ? handleGenerate : undefined}
          />
        </View>

      </ScrollView>
    </KeyboardAvoidingView>
  );
}

const styles = StyleSheet.create({
  flex: { flex: 1 },

  scroll: {
    flex: 1,
    backgroundColor: colors.bg.primary,
  },

  content: {
    paddingHorizontal: space[12],
    paddingTop: space[8],
    paddingBottom: space[24],
  },

  // ── Greeting ──
  greetingSection: {
    marginBottom: space[10],
  },

  dateLabel: {
    fontSize: font.size.sm,
    color: colors.text.muted,
    fontWeight: font.weight.regular,
    marginBottom: 4,
  },

  greeting: {
    fontSize: 22,
    fontWeight: font.weight.light,
    color: colors.text.primary,
    letterSpacing: -0.3,
    lineHeight: 28,
  },

  errorBanner: {
    backgroundColor: "#FCEAEB",
    borderRadius: radius.md,
    padding: space[4],
    marginBottom: space[6],
  },

  errorText: {
    fontSize: font.size.sm,
    color: "#8A2030",
    textAlign: "center",
  },

  // ── Intention ──
  intentionSection: {
    marginBottom: space[8],
    alignItems: "center",
  },

  intentionPrompt: {
    fontSize: 26,
    fontWeight: font.weight.medium,
    color: colors.text.primary,
    letterSpacing: -0.5,
    lineHeight: 33,
    marginBottom: space[8],
    textAlign: "center",
  },

  intentionInput: {
    width: "100%",
    paddingVertical: space[3],
    paddingHorizontal: 0,
    borderBottomWidth: 1,
    borderBottomColor: "#E0E0DE",
    fontSize: font.size.lg,
    color: colors.text.primary,
    backgroundColor: "transparent",
    textAlign: "center",
  },

  // ── Tasks ──
  section: {
    marginBottom: space[5],
  },

  tasksToggle: {
    ...cardBase,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: space[5],
    paddingHorizontal: space[8],
  },

  tasksToggleLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: space[4],
  },

  tasksToggleLabel: {
    fontSize: font.size.base,
    fontWeight: font.weight.medium,
    color: colors.text.primary,
  },

  tasksBadge: {
    backgroundColor: "#EBEBEB",
    borderRadius: radius.full,
    paddingHorizontal: 7,
    paddingVertical: 1,
    minWidth: 20,
    alignItems: "center",
  },

  tasksBadgeText: {
    fontSize: font.size.xs,
    fontWeight: font.weight.semibold,
    color: colors.text.secondary,
  },

  chevron: {
    fontSize: 18,
    color: colors.text.muted,
    fontWeight: font.weight.light,
    lineHeight: 22,
  },

  tasksBody: {
    ...cardBase,
    padding: space[8],
    marginTop: 4,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
  },

  taskRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: space[6],
    paddingVertical: space[6],
  },

  taskRowBorder: {
    borderBottomWidth: 0.5,
    borderBottomColor: "#F0F0EE",
  },

  taskContent: {
    flex: 1,
    gap: space[3],
  },

  taskName: {
    fontSize: font.size.base,
    color: colors.text.primary,
    lineHeight: 20,
  },

  effortRow: {
    flexDirection: "row",
    gap: space[2],
  },

  effortTag: {
    paddingVertical: 3,
    paddingHorizontal: space[4],
    borderRadius: radius.sm,
  },

  effortTagInactive: {
    backgroundColor: "#F2F2F0",
  },

  effortTagText: {
    fontSize: font.size.tiny,
    fontWeight: font.weight.regular,
  },

  removeBtn: {
    width: 28,
    height: 28,
    alignItems: "center",
    justifyContent: "center",
  },

  removeBtnText: {
    fontSize: 20,
    color: "#D0D0CC",
    lineHeight: 24,
  },

  addTaskForm: {
    gap: space[4],
    paddingTop: space[5],
  },

  addTaskInputRow: {
    flexDirection: "row",
    gap: space[3],
  },

  addTaskInput: {
    flex: 1,
    paddingVertical: space[4],
    paddingHorizontal: space[5],
    borderWidth: 1,
    borderColor: "#E8E8E6",
    borderRadius: radius.sm,
    fontSize: font.size.base,
    color: colors.text.primary,
    backgroundColor: colors.bg.surface,
  },

  addBtn: {
    paddingVertical: space[4],
    paddingHorizontal: space[8],
    backgroundColor: colors.accent,
    borderRadius: radius.sm,
    justifyContent: "center",
  },

  addBtnText: {
    fontSize: font.size.sm,
    color: colors.text.inverse,
    fontWeight: font.weight.semibold,
  },

  cancelBtn: {
    alignSelf: "flex-start",
  },

  cancelBtnText: {
    fontSize: font.size.sm,
    color: colors.text.secondary,
  },

  addTaskDashed: {
    width: "100%",
    paddingVertical: space[5],
    borderWidth: 1,
    borderColor: "#DCDCD8",
    borderStyle: "dashed",
    borderRadius: radius.md,
    alignItems: "center",
    marginTop: space[3],
  },

  addTaskDashedText: {
    fontSize: font.size.sm,
    color: colors.text.muted,
  },

  // ── Divider ──
  divider: {
    height: 0.5,
    backgroundColor: "rgba(0,0,0,0.07)",
    marginVertical: space[8],
  },

  // ── Metrics ──
  metricsRow: {
    flexDirection: "row",
    gap: space[4],
    marginBottom: space[5],
  },
});
